### ISSUE TITLE
🐛 Animation to bottom may be called too soon

### ISSUE THREAD

**Issue by aguilaair** [papercups-io/papercups_flutter#43]
The animation may be called to soon, causing errors.

To address this we must make sure that the ScrollController has clients and the WidgetBindings is not null.

**Comment by aguilaair** [comment]
The last issue remaining seems to be web only, would love some help as I cannot quite figure out why this is happening:

```
Error: Unexpected null value.
    at Object.throw_ [as throw] (http://localhost:60712/dart_sdk.js:4354:11)
    at Object.nullCheck (http://localhost:60712/dart_sdk.js:4687:30)
    at scroll_position_with_single_context.ScrollPositionWithSingleContext.new.didEndScroll (http://localhost:60712/packages/flutter/src/widgets/widget_span.dart.lib.js:32434:89)
    at scroll_position_with_single_context.ScrollPositionWithSingleContext.new.beginActivity (http://localhost:60712/packages/flutter/src/widgets/widget_span.dart.lib.js:32415:82)
    at scroll_position_with_single_context.ScrollPositionWithSingleContext.new.beginActivity (http://localhost:60712/packages/flutter/src/widgets/widget_span.dart.lib.js:32603:13)
    at scroll_position_with_single_context.ScrollPositionWithSingleContext.new.goIdle (http://localhost:60712/packages/flutter/src/widgets/widget_span.dart.lib.js:32615:12)
    at scroll_position_with_single_context.ScrollPositionWithSingleContext.new.goBallistic (http://localhost:60712/packages/flutter/src/widgets/widget_span.dart.lib.js:32624:14)
    at scroll_activity.DrivenScrollActivity.new.[_end] (http://localhost:60712/packages/flutter/src/widgets/widget_span.dart.lib.js:33308:21)
    at _RootZone.run (http://localhost:60712/dart_sdk.js:37849:58)
    at _FutureListener.whenComplete.handleWhenComplete (http://localhost:60712/dart_sdk.js:32834:29)
    at handleWhenCompleteCallback (http://localhost:60712/dart_sdk.js:33332:43)
    at Function._propagateToListeners (http://localhost:60712/dart_sdk.js:33398:15)
```
